name: Improve Docs
description: Something isn't described correctly in the documentation, needs to be updated, missing, or badly structured? Here is the right place to report.
title: "<short description>"
labels: ["unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation. Please complete the following so we can have the necessary details about your suggestion.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a new issue.
      options:
        - label: My suggestion/issue is about the [latest version of the documentation](https://docs.fetch.ai/).
          required: true
        - label: I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure my problem has not already been reported.
          required: true
        - label: I have read the [code of conduct](https://github.com/fetchai/docs/blob/master/CODE_OF_CONDUCT.md) before creating this issue.
          required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project is this issue about?
      options:
        - Ledger
        - CosmPy
        - Fetch Wallet
        - AEA Framework
        - Collective Learning
        - Something else
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What is this issue about?
      options:
        - Bug
        - Something is missing
        - Something needs improving (e.g. is badly explained)
        - Something is wrong
        - General suggestion
        - Something else
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: More details
      description: Give a detailed description of the bug/improvement/suggestion.
    validations:
      required: true
  - type: textarea
    id: permalink
    attributes:
      label: Relevant Section(s)
      description: Insert the links to the relevant section(s) in the docs. Choose the most specific section / lowest-level heading to which your suggested change applies.
      placeholder: "For example: https://docs.fetch.ai/CosmPy/query-balance/"
    validations:
      required: false
  - type: textarea
    id: assets
    attributes:
      label: Assets
      description: Include any relevant files or links here.
    validations:
      required: false
