site_name: Etch Language Docs
# site_url:
site_description: Everything you need to know about `etch`. 
repo_url: https://github.com/fetchai
repo_name: 'GitHub'
site_author: katharine.murphy@fetch.ai and ruth.brennan@fetch.ai

theme:
  name: readthedocs
  custom_dir: custom_theme/

nav:
  - Welcome:
      - "What's etch?": 'index.md'
      - 'Getting started': 'getstarted.md'
      - 'Debugging': 'debug.md'
  - The basics:
      - 'Syntax': 'syntax.md'
      - 'Variables': 'variables.md'
      - 'Operators': 'operators.md'
      - 'Logical operators': 'logic.md'
      - 'Control flow': 'control-flow.md'
      - 'Strings': 'strings.md'
      - 'Arrays': 'arrays.md'
      - 'Functions': 'functions.md'
      - 'Error checking': 'error-checking.md'
  - Smart contracts:
      - 'Introduction': 'smart-contract-intro.md'
      - 'Executing smart contract code': 'executing-smart-contract-code.md'
      - 'States': 'states.md'
      - 'Memory': 'memory.md'
      - 'Addresses': 'addresses.md'
      - 'Transactions': 'transactions.md'
      - 'Smart contracts': 'smart-contracts.md'
  - Machine learning:
      - 'Machine learning and AI': 'ML-AI.md'
      - 'Maths libraries and functions': 'maths-libs.md'
  - Extending etch:
      - 'Extending etch in C++': 'extending-etch.md'
  - Examples: 
      - 'Fetch logo': 'examples/fetch-logo.md'
      - '2D array': 'examples/2d-array.md'
      - 'Mandelbrot': 'examples/mandelbrot.md'
      - 'Searching algorithms': 'examples/searching-algorithms.md'
      - 'Sorting algorithms': 'examples/sorting-algorithms.md'

markdown_extensions:
# - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css

