@startuml
package Legend {
    component "UML component" as c2

    component "UML component with port" as c1 {
        port "        port " as p1
    }


    c2 <-- c1 : "Uses in-process\n\n"
    c2 <.. p1 : "Uses over network"
}
@enduml
