@startuml
package legend {
    entity Parent
    entity Child {
        parent
    }

    Child::parent ..|| Parent : "API accessor"
    Parent ||--|{ Child : "   Foreign Key Relation"

    entity Entity {
      +indexed field
      non-indexed field
    }

    entity Other {}

    Entity -|| Other : "Exactly one"
    Entity -|{ Other : "One or many"
    Entity .o{ Other : "Zero or many"
}
@enduml
