name: Deployment

on:
  push:
    branches:
      - feature/automatic-deployment
    # paths:
    #   - 'docs/**'

jobs:
  build:
    name: Docs Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: pip3 install pipenv && pipenv install

      - name: Build
        run: pipenv run mkdocs build

      - name: Deploy
        run: pipenv run mkdocs gh-deploy


