name: Docs sanity checks and tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  common_checks:
    continue-on-error: False
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'true'
      - uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tox
      - name: Generate Documentation
        run: tox -e docs
